### ISSUE TITLE
Background bug

### ISSUE THREAD

**Issue by MaximovInk** [jakubshark/PixelGameEngine#2]
I get a black screen on startup. If i delete this code in PixelGameEngine:132 background.Pixels.CopyTo(Graphics.GetDrawTarget().Pixels, 0);
then all is well, but background don't work.
![image](https://user-images.githubusercontent.com/38013889/49543543-8f4c2280-f8e9-11e8-88a1-8739651b8c09.png)

**Comment by jakubshark** [comment]
Btw Are you on One Lone Coder discord?
